
[engine]
max_timeout = 4
closing_timeout = 2

[logging]
tick_interval = 20
level = "DEBUG"

[[servers]]
server_name = "bureau of odd things"
root = "www/bureau"

	[[servers.bindings]]
	host = "localhost"
	service = "8080"

	[servers.errors]
	404 = "errors/404.html"
	500 = "errors/500.html"
	403 = "errors/403.html"

	# Static files route
	[[servers.routes]]
	handler = "STATIC"
	path = "/"
	alias = "/static/"
	methods = ["GET"]
	index = "index.html"
	autoindex = false

	[[servers.routes]]
	handler = "REDIRECT"
	path = "/redirectionhihi"
	methods = ["GET"]
	location = "/"
	status = "303"

	[[servers.routes]]
	path = "/api"
	methods = ["GET", "POST"]
	handler = "CGI"
	default_bin = "api.py"
	interpreters = {py = "python3"}
	cgi_timeout = 10
	env = {}

	[[servers.routes]]
	path = "/status"
	methods = ["GET"]
	handler = "STATUS"
	show_start_time = true
	show_server_info = true
	show_connection_info = true
	show_request_info = true
	show_timestamp = true
